apiVersion: v1
kind: ConfigMap
metadata:
  name: excerpt-service-api-properties
data:
  config.yaml: |-
    server.max-http-header-size: 32KB
    data-platform:
      datasource:
        url: jdbc:postgresql://{{.Values.db.url}}:{{.Values.db.port}}/{{.Values.db.name}}
        connection-timeout: {{.Values.db.connectionTimeout}}
      kafka:
        bootstrap: {{ .Values.kafka.service }}
        topic-properties:
          num-partitions: {{ .Values.kafka.numPartitions }}
          replication-factor: {{ .Values.global.kafkaOperator.replicationFactor }}

    dso:
      url: {{ .Values.dso.url }}

    request-signature-ceph:
      http-endpoint: {{ .Values.requestSignatureCeph.httpEndpoint }}
      bucketName: {{ .Values.requestSignatureCeph.bucketName }}
    datafactory-excerpt-ceph:
      http-endpoint: {{ .Values.datafactoryExcerptCeph.httpEndpoint }}
      bucketName: {{ .Values.datafactoryExcerptCeph.bucketName }}
    excerpt-signature-ceph:
      http-endpoint: {{ .Values.excerptSignatureCeph.httpEndpoint }}
      bucketName: {{ .Values.excerptSignatureCeph.bucketName }}

    logging:
      level:
        org.zalando.logbook: TRACE
